name: Build Gentoo SystemD kernel
on:
  workflow_call:
    inputs:
      _cpusched:
        required: true
        type: string
      compiler:
        required: true
        type: string

env:
  _distro: "Gentoo"
  _IS_GHCI: "true"

jobs:
  build-kernel:
    env:
      _cpusched: ${{ inputs._cpusched }}
      compiler: ${{ inputs.compiler }}
    runs-on: ubuntu-latest
    container: ghcr.io/the-kernel-toolkit/tkt-gentoo-systemd-dev:latest

    steps:
      - name: Checkout TKT
        uses: actions/checkout@v4

      - name: Adjust compiler and compile Kernel
        env:
          _cpusched: ${{ inputs._cpusched }}
          compiler: ${{ inputs.compiler }}
          CC: x86_64-pc-linux-gnu
        shell: bash
        run: |
          source /etc/environment
          git config --global --add safe.directory "$(pwd)"
          if [ "${{ inputs.compiler }}" = "llvm" ] || [ "${{ inputs.compiler }}" = "clang" ]; then
            export KCFLAGS="$KCFLAGS -Wno-error -Wno-unused-command-line-argument"
          fi
          sed -i 's/^_distro=".*"/_distro="Gentoo"/' customization.cfg
          sed -i 's/^_compiler=".*"/_compiler="${{ inputs.compiler }}"/' customization.cfg
          set +o pipefail
          yes '' | ./install.sh install || true
          set -o pipefail

          # Adapt for Gentoo from here down
      - name: Package Gentoo files
        run: |
          tar czf Gentoo-SystemD-linux-diet-${{ env._cpusched }}-${{ inputs.compiler }}.tar.gz */*.whatever

      - uses: actions/upload-artifact@v4
        with:
          name: gentoo-systemd-kernel-packages-${{ env._cpusched }}-${{ inputs.compiler }}
          path: Gentoo-SystemD-linux-*.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          name: "Gentoo SystemdD Kernel Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: Gentoo-SystemD-linux-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
