name: Build Slackware kernel

on:
  workflow_call:
    inputs:
      _cpusched:
        required: true
        type: string
      compiler:
        required: true
        type: string

env:
  _distro: "Slackware"
  _IS_GHCI: "true"

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container: ghcr.io/the-kernel-toolkit/tkt-slackware-dev:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_SSL_CAINFO: /etc/ssl/certs/ca-certificates.crt

    steps:
      - name: Checkout TKT
        uses: actions/checkout@v4

      - name: Adjust compiler and compile Kernel
        shell: bash
        env:
          _cpusched: ${{ inputs._cpusched }}
          compiler: ${{ inputs.compiler }}
        run: |
          source /etc/environment
          git config --global --add safe.directory "$(pwd)"
          git config --global http.sslCAInfo /etc/ssl/certs/ca-certificates.crt
          sed -i 's/^_distro=".*"/_distro="Slackware"/' customization.cfg
          sed -i 's/^_compiler=".*"/_compiler="${{ inputs.compiler }}"/' customization.cfg
          yes '' | bash ./install.sh install || true

      - uses: actions/upload-artifact@v4
        with:
          name: slackware-kernel-packages-${{ inputs._cpusched }}-${{ inputs.compiler }}
          path: "*/*.txz"

      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Slackware Kernel Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: "*/*.txz"
